### DISCUSSION TITLE
Run in a docker compose

### DISCUSSION THREAD

**Discussion by noahfraiture** [av/harbor#133] [Q&A]
Hello,

I'm struggling to find any information about that. I would like to run this on a VPS and I manage that VPS with docker stack containing a reverse proxy to redirect my http request depening on the Host. So basically my current service is the following 
```
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    labels :
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`open.noahcode.dev`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls.certresolver=myresolver"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - traefik
```

However I would like to use harbor, and I can easily install it on the server, and use the command but I don't find a way to point my reverse proxy to a service on the host, so I would like to run harbor as a container itself, and I could enter in that container to run the harbor command easily.
Is it possible to have a docker image with harbor ? And most important, is there a volume to create for persistency ? What directory are important for the persistency ?
