### ISSUE TITLE
Nvidia CDI driver support and Podman

### ISSUE THREAD

**Issue by FrantaNautilus** [av/harbor#101]
If I understand correctly the current support for Nvidia GPUs relies on using adding appropriate `compose.x.<service>.nvidia.yml` file to the compose files loaded with docker-compose, these contain the device description:
```
devices:
  - driver: nvidia
    count: all
    capabilities: [gpu]
```
This is a problem for systems relying on CDI driver for the Nvidia support for containers, such as NixOS. Allowing the user to change this section based on the system configuration would also (partialy) enable use of Podman instead of Docker, since the former relies on CDI. The section for CDI system would look like:
```
devices:
  - driver: cdo
    capabilities: [gpu]
    device_ids:
    - nvidia.com/gpu=all
```
I have tested this change for ollama + webui and it does work.

Another problem is that on CDI system such as NixOS the detection of `nvidia-ctk` fails even though `nvidia-container-toolkit` works. This could be solved by adding an "force-nvidia" variable which would allow to force Nvidia even though the checks fail.

Regarding Podman, the only place where it is currently not compatible apart from Nvidia seems to be the `--wait` flag for `docker compose`, this may be fixed in future releases of Podman.
