### ISSUE TITLE
How can I have Harbor build an image from the latest Github commit, e.g. VLLM?

### ISSUE THREAD

**Issue by ColumbusAI** [av/harbor#110]
Even thinking if this is possible, is it also possible to have a PR release added to the image?

**Comment by av** [comment]
In theory you can, in practice it'll be complicated since you'll have to replicate service's required build environment locally. There are a couple of approaches, all based on using Docker's support for `git` context.

**Approach 1**

Replace `build` with git repo context, I took the build args from here: https://github.com/vllm-project/vllm/blob/main/.buildkite/release-pipeline.yaml#L6

```yaml
    build:
      # context: ./vllm
      # dockerfile: Dockerfile
      # args:
      #   HARBOR_VLLM_VERSION: ${HARBOR_VLLM_VERSION}
      context: https://github.com/vllm-project/vllm.git#main
      dockerfile: Dockerfile
      args:
        max_jobs: 16
        USE_SCCACHE: 0
        GIT_REPO_CHECK: 0
        CUDA_VERSION: 12.1.0
```

**Approach 2**

Use repo context in the `$(harbor home)/vllm/Dockerfile`:

```bash
FROM https://github.com/vllm-project/vllm.git as source
# ... Paste original Dockerfile
# 1. Replace COPY with COPY --from=source
# 2. Build the "vllm-openai" stage
```

I briefly tried both, but they do not work right away and further debug is required
