### ISSUE TITLE
Perplexica UI doesn't terminate initialization

### ISSUE THREAD

**Issue by PieBru** [av/harbor#70]
Hi,
Trying Perplexica, it installs without errors, but the UI is stuck before writing its "prompt". It seems its settings must be adjusted, but also the settings page remains stuck waiting with the `UPLOAD` button disabled:
![image](https://github.com/user-attachments/assets/0483632a-389e-43f7-b37c-6bca12f064ee)

It seems also that Perplexica doesn't take advantage of the Harbor ecosystem (Ollama, SearXNG).

I got Perplexica working in a dedicated LXC container after setting its `config.toml` before starting it:
```toml
[API_KEYS]
GROQ = "gsk_******"

[API_ENDPOINTS]
OLLAMA = "http://10.4.0.100:11434"
SEARXNG = "http://10.4.0.105:4000"
```

The only harbor config I'm aware of is this:
```bash
[root@HarborAI ~]# harbor config ls | grep -i perplexica
PERPLEXICA_HOST_PORT           34041
PERPLEXICA_BACKEND_HOST_PORT   34042
```

How to solve?
Thank you

**Comment by av** [comment]
Thanks for the report, it's not an expected state, since Perplexica should:
- Start from scratch with `harbor up perplexica`
- Connect to built-in Ollama and Searxng out of the box

Unfortunately, Perplexica is one of the services that are a tiny bit "picky" in terms of configuration, I've outlined some most possible caveats here: https://github.com/av/harbor/issues/60#issuecomment-2411864309

---

> The only harbor config I'm aware of

Perplexica (and many other services) cross-connections are setup with [cross-service files](https://github.com/av/harbor/wiki/6.-Harbor-Compose-Setup#cross-service-file) (I call them `x` files, haha), here's [one for Ollama](https://github.com/av/harbor/blob/main/compose.x.perplexica.ollama.yml) and another one for [SearXNG](https://github.com/av/harbor/blob/main/compose.x.perplexica.searxng.yml), these are merged with the rest of the configs whenever harbor sees that matching services are run together (including default services). So one of the things to check is to verify if values in these files match the expected network layout.

**Comment by nullnuller** [comment]
I still have the same issue https://github.com/av/harbor/issues/60#issuecomment-2411864309
Also, I noticed that perplexica config survives rm -rf harbor

**Comment by PieBru** [comment]
I managed to solve this same issue I had with Perplexica in a LXC container on Proxmox VE, but I don't know how to apply this solution to Perplexica on Harbor.

After finding this https://github.com/ItzCrazyKns/Perplexica/issues/467, the solution was substituting `127.0.0.1` with the LAN IP of the computer runnong Harbor, in my case `10.4.0.174`, into `docker-compose.yaml`:

```yaml
perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
```

**Comment by ecker00** [comment]
This requires rebuilding the image, if you are lazy override it on runtime:

```
  perplexica-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    restart: unless-stopped
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    command: >
      sh -c "
      find .next -type f -name '*.js' -exec sed -i 's|ws://127.0.0.1:3001|ws://10.0.5.100:3001|g' {} + &&
      find .next -type f -name '*.js' -exec sed -i 's|http://127.0.0.1:3001/api|http://10.0.5.100:3001/api|g' {} + &&
      yarn start"
 ```
