### ISSUE TITLE
can't recognize system's self signed certificate in chain

### ISSUE THREAD

**Issue by shenhai-ran** [av/harbor#90]
I am using Harbor to host applications such as dify, n8n. However since I have self-signed certificate, some applications have trouble to communicate with outside. 

For example, if I add Groq API keys in `n8n`, I have error for this
![image](https://github.com/user-attachments/assets/e5baa63f-9abd-44d6-8718-f03ec78d12ec)

For the environment, I am using WSL2, and the self-signed certificate is added to the system already.

How can I let Harbor and its services recognize the system certificate?

Thanks for your help.

**Comment by av** [comment]
Hey, thanks for trying out Harbor!

As per my understanding it happens because the custom certificates are not installed in the service containers, so the container OS doesn't know about them and won't mark them as trusted.

One way to verify if that's the case is to add a custom mount to one of the affected services (dify or n8n as you mentioned).

You can open Harbor workspace in the IDE and edit the related compose files directly for the purposes of the test:

```bash
# Helper to open the workspace in VS Code
harbor code

# Otherwise, use your preferred IDE at this location
harbor home
```

n8n
```yaml
n8n:
  # ...
  volumes:
  # ...
    # Replace the /path/to/certs with your actual path
    -  /path/to/certs:/usr/local/share/ca-certificates:ro
```

**Comment by shenhai-ran** [comment]
Hello,

Thanks for your feedback, I found similar results online :).  However particularly for n8n, besides update volumes, I also need to add one more environment variable in the yml file as:
``` yaml
 n8n:
  # ...
    volumes:
      # ...
      -  /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment::
      # ...
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
 ```

This works for at least `Groq` and I think it should also work for others.

I guess since no running of `update-ca-certificates` in the Docker image, what ever certificates put at `/usr/local/share/ca-certificates` don't really take any effects. So I have to copy `/etc/ssl/certs/ca-certificates.crt` (for Ubuntu) to the image.
Then environment variable is also necessary for me. Maybe better solution is the add something like `HARBOR_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` at `.env`, so I can reuse it.

Thanks anyway, I will try other service to see if it works for all :)
