### ISSUE TITLE
Add KoboldCpp

### ISSUE THREAD

**Issue by henk717** [av/harbor#99]
I think it would be nice to have KoboldCpp supported by the project, its both a backend and has its own UI.
The undelying engine of KoboldCpp is a fork of llamacpp, stable-diffusion.cpp, whisper.cpp and others.

The official docker-compose for the project is as follows:
```
version: "3.2"
services:
  koboldcpp:
    container_name: koboldcpp
    image: koboldai/koboldcpp:latest
    volumes:
      - ./kcpp-data:/workspace/:rw
    deploy: # You can remove this section if you do not wish to use an Nvidia GPU
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    environment:
      - KCPP_MODEL=https://huggingface.co/concedo/KobbleTinyV2-1.1B-GGUF/resolve/main/KobbleTiny-Q4_K.gguf?download=true # Remove this line if you wish to supply your own model offline
      - KCPP_DONT_REMOVE_MODELS=true
      - KCPP_DONT_UPDATE=false
      - KCPP_DONT_TUNNEL=true
      - KCPP_ARGS=--model model.gguf --usecublas --gpulayers 99 --multiuser 20 --quiet # Remove --model model.gguf if you are using a comma split model with the KCPP_MODEL argument, remove --usecublas --gpulayers 99 --multiuser 20 for CPU mode
    ports:
      - "5001:5001"
 ```

If this project needs a different design I can help with that, but I am not familair enough with this project to do a PR from scratch.

KoboldCpp supports its own API, OpenAI's API (multiple including stuff like image recognition) and even has some basic ollama emulation. Should make it work with a lot of the frontends in this project.
